export type BibleBook = {
  number: number;
  english: string;
  korean: string;
  chapters: number;
};

export const BIBLE_BOOKS: BibleBook[] = [
  { number: 1, english: "Genesis", korean: "창세기", chapters: 50 },
  { number: 2, english: "Exodus", korean: "출애굽기", chapters: 40 },
  { number: 3, english: "Leviticus", korean: "레위기", chapters: 27 },
  { number: 4, english: "Numbers", korean: "민수기", chapters: 36 },
  { number: 5, english: "Deuteronomy", korean: "신명기", chapters: 34 },
  { number: 6, english: "Joshua", korean: "여호수아", chapters: 24 },
  { number: 7, english: "Judges", korean: "사사기", chapters: 21 },
  { number: 8, english: "Ruth", korean: "룻기", chapters: 4 },
  { number: 9, english: "1 Samuel", korean: "사무엘상", chapters: 31 },
  { number: 10, english: "2 Samuel", korean: "사무엘하", chapters: 24 },
  { number: 11, english: "1 Kings", korean: "열왕기상", chapters: 22 },
  { number: 12, english: "2 Kings", korean: "열왕기하", chapters: 25 },
  { number: 13, english: "1 Chronicles", korean: "역대상", chapters: 29 },
  { number: 14, english: "2 Chronicles", korean: "역대하", chapters: 36 },
  { number: 15, english: "Ezra", korean: "에스라", chapters: 10 },
  { number: 16, english: "Nehemiah", korean: "느헤미야", chapters: 13 },
  { number: 17, english: "Esther", korean: "에스더", chapters: 10 },
  { number: 18, english: "Job", korean: "욥기", chapters: 42 },
  { number: 19, english: "Psalms", korean: "시편", chapters: 150 },
  { number: 20, english: "Proverbs", korean: "잠언", chapters: 31 },
  { number: 21, english: "Ecclesiastes", korean: "전도서", chapters: 12 },
  { number: 22, english: "Song of Solomon", korean: "아가", chapters: 8 },
  { number: 23, english: "Isaiah", korean: "이사야", chapters: 66 },
  { number: 24, english: "Jeremiah", korean: "예레미야", chapters: 52 },
  { number: 25, english: "Lamentations", korean: "예레미야애가", chapters: 5 },
  { number: 26, english: "Ezekiel", korean: "에스겔", chapters: 48 },
  { number: 27, english: "Daniel", korean: "다니엘", chapters: 12 },
  { number: 28, english: "Hosea", korean: "호세아", chapters: 14 },
  { number: 29, english: "Joel", korean: "요엘", chapters: 3 },
  { number: 30, english: "Amos", korean: "아모스", chapters: 9 },
  { number: 31, english: "Obadiah", korean: "오바댜", chapters: 1 },
  { number: 32, english: "Jonah", korean: "요나", chapters: 4 },
  { number: 33, english: "Micah", korean: "미가", chapters: 7 },
  { number: 34, english: "Nahum", korean: "나훔", chapters: 3 },
  { number: 35, english: "Habakkuk", korean: "하박국", chapters: 3 },
  { number: 36, english: "Zephaniah", korean: "스바냐", chapters: 3 },
  { number: 37, english: "Haggai", korean: "학개", chapters: 2 },
  { number: 38, english: "Zechariah", korean: "스가랴", chapters: 14 },
  { number: 39, english: "Malachi", korean: "말라기", chapters: 4 },
  { number: 40, english: "Matthew", korean: "마태복음", chapters: 28 },
  { number: 41, english: "Mark", korean: "마가복음", chapters: 16 },
  { number: 42, english: "Luke", korean: "누가복음", chapters: 24 },
  { number: 43, english: "John", korean: "요한복음", chapters: 21 },
  { number: 44, english: "Acts", korean: "사도행전", chapters: 28 },
  { number: 45, english: "Romans", korean: "로마서", chapters: 16 },
  { number: 46, english: "1 Corinthians", korean: "고린도전서", chapters: 16 },
  { number: 47, english: "2 Corinthians", korean: "고린도후서", chapters: 13 },
  { number: 48, english: "Galatians", korean: "갈라디아서", chapters: 6 },
  { number: 49, english: "Ephesians", korean: "에베소서", chapters: 6 },
  { number: 50, english: "Philippians", korean: "빌립보서", chapters: 4 },
  { number: 51, english: "Colossians", korean: "골로새서", chapters: 4 },
  { number: 52, english: "1 Thessalonians", korean: "데살로니가전서", chapters: 5 },
  { number: 53, english: "2 Thessalonians", korean: "데살로니가후서", chapters: 3 },
  { number: 54, english: "1 Timothy", korean: "디모데전서", chapters: 6 },
  { number: 55, english: "2 Timothy", korean: "디모데후서", chapters: 4 },
  { number: 56, english: "Titus", korean: "디도서", chapters: 3 },
  { number: 57, english: "Philemon", korean: "빌레몬서", chapters: 1 },
  { number: 58, english: "Hebrews", korean: "히브리서", chapters: 13 },
  { number: 59, english: "James", korean: "야고보서", chapters: 5 },
  { number: 60, english: "1 Peter", korean: "베드로전서", chapters: 5 },
  { number: 61, english: "2 Peter", korean: "베드로후서", chapters: 3 },
  { number: 62, english: "1 John", korean: "요한일서", chapters: 5 },
  { number: 63, english: "2 John", korean: "요한이서", chapters: 1 },
  { number: 64, english: "3 John", korean: "요한삼서", chapters: 1 },
  { number: 65, english: "Jude", korean: "유다서", chapters: 1 },
  { number: 66, english: "Revelation", korean: "요한계시록", chapters: 22 },
];

export const getBibleBookByKorean = (korean: string): BibleBook | undefined =>
  BIBLE_BOOKS.find((book) => book.korean === korean);
