// src/constants/errorBehaviorMap.ts
import {
  COGNITIVE_BEHAVIOR_ID,
  COGNITIVE_BEHAVIORS,
  type CognitiveBehaviorId,
} from "./behaviors";
import { COGNITIVE_ERROR_ID, type CognitiveErrorId } from "./errors";

/**
 * ✅ 인지오류 -> 추천 치유기법(순서대로)
 * - 배열 순서가 곧 추천 순서(①②③...)
 */
export const COGNITIVE_ERROR_RECOMMENDED_BEHAVIOR_IDS = {
  // 1. 흑백논리(=전부 아니면 전무)
  [COGNITIVE_ERROR_ID.ALL_OR_NOTHING]: [
    COGNITIVE_BEHAVIOR_ID.DOUBLE_STANDARD,
    COGNITIVE_BEHAVIOR_ID.COST_BENEFIT,
    COGNITIVE_BEHAVIOR_ID.BE_SPECIFIC,
    COGNITIVE_BEHAVIOR_ID.SEMANTIC_METHOD,
  ],

  // 2. 과도한 일반화(=과잉일반화)
  [COGNITIVE_ERROR_ID.OVERGENERALIZATION]: [
    COGNITIVE_BEHAVIOR_ID.DOUBLE_STANDARD,
    COGNITIVE_BEHAVIOR_ID.COST_BENEFIT,
    COGNITIVE_BEHAVIOR_ID.BE_SPECIFIC,
    COGNITIVE_BEHAVIOR_ID.EXAMINE_EVIDENCE,
    COGNITIVE_BEHAVIOR_ID.SEMANTIC_METHOD,
  ],

  // 3. 비판 하나만 크게 보기(=정신적 여과)
  [COGNITIVE_ERROR_ID.MENTAL_FILTER]: [
    COGNITIVE_BEHAVIOR_ID.DOUBLE_STANDARD,
    COGNITIVE_BEHAVIOR_ID.COST_BENEFIT,
    COGNITIVE_BEHAVIOR_ID.BE_SPECIFIC,
    COGNITIVE_BEHAVIOR_ID.EXAMINE_EVIDENCE,
    COGNITIVE_BEHAVIOR_ID.RE_ATTRIBUTION,
  ],

  // 4. 긍정적인 것 무시하기(=긍정 무시)
  [COGNITIVE_ERROR_ID.DISCOUNTING_POSITIVE]: [
    COGNITIVE_BEHAVIOR_ID.DOUBLE_STANDARD,
    COGNITIVE_BEHAVIOR_ID.COST_BENEFIT,
    COGNITIVE_BEHAVIOR_ID.BE_SPECIFIC,
    COGNITIVE_BEHAVIOR_ID.EXAMINE_EVIDENCE,
    COGNITIVE_BEHAVIOR_ID.RE_ATTRIBUTION,
  ],

  // 5. 성급하게 생각하기(상대 생각 읽기/잘못된 미래 믿음)(=성급한 결론)
  [COGNITIVE_ERROR_ID.JUMPING_TO_CONCLUSIONS]: [
    COGNITIVE_BEHAVIOR_ID.DOUBLE_STANDARD,
    COGNITIVE_BEHAVIOR_ID.COST_BENEFIT,
    COGNITIVE_BEHAVIOR_ID.BE_SPECIFIC,
    COGNITIVE_BEHAVIOR_ID.EXAMINE_EVIDENCE,
  ],

  // 6. 부풀리기/무시하기(=확대와 축소)
  [COGNITIVE_ERROR_ID.MAGNIFICATION_MINIMIZATION]: [
    COGNITIVE_BEHAVIOR_ID.DOUBLE_STANDARD,
    COGNITIVE_BEHAVIOR_ID.COST_BENEFIT,
    COGNITIVE_BEHAVIOR_ID.BE_SPECIFIC,
    COGNITIVE_BEHAVIOR_ID.EXAMINE_EVIDENCE,
    COGNITIVE_BEHAVIOR_ID.SEMANTIC_METHOD,
  ],

  // 7. 감정적으로만 판단하기(=감정적 추론)
  [COGNITIVE_ERROR_ID.EMOTIONAL_REASONING]: [
    COGNITIVE_BEHAVIOR_ID.DOUBLE_STANDARD,
    COGNITIVE_BEHAVIOR_ID.COST_BENEFIT,
    COGNITIVE_BEHAVIOR_ID.BE_SPECIFIC,
    COGNITIVE_BEHAVIOR_ID.EXAMINE_EVIDENCE,
    COGNITIVE_BEHAVIOR_ID.RE_ATTRIBUTION,
  ],

  // 8. 반드시 해야 한다는 생각(=당위적 진술)
  [COGNITIVE_ERROR_ID.SHOULD_STATEMENTS]: [
    COGNITIVE_BEHAVIOR_ID.DOUBLE_STANDARD,
    COGNITIVE_BEHAVIOR_ID.COST_BENEFIT,
    COGNITIVE_BEHAVIOR_ID.EXAMINE_EVIDENCE,
    COGNITIVE_BEHAVIOR_ID.SEMANTIC_METHOD,
  ],

  // 9. 낙인 찍기(=이름 붙이기)
  [COGNITIVE_ERROR_ID.LABELING]: [
    COGNITIVE_BEHAVIOR_ID.DOUBLE_STANDARD,
    COGNITIVE_BEHAVIOR_ID.COST_BENEFIT,
    COGNITIVE_BEHAVIOR_ID.BE_SPECIFIC,
    COGNITIVE_BEHAVIOR_ID.EXAMINE_EVIDENCE,
    COGNITIVE_BEHAVIOR_ID.SEMANTIC_METHOD,
    COGNITIVE_BEHAVIOR_ID.RE_ATTRIBUTION,
  ],

  // 10. 과도한 비난(=개인화에 가까움: 자기/타인 탓으로 몰아가기)
  [COGNITIVE_ERROR_ID.PERSONALIZATION]: [
    COGNITIVE_BEHAVIOR_ID.DOUBLE_STANDARD,
    COGNITIVE_BEHAVIOR_ID.COST_BENEFIT,
    COGNITIVE_BEHAVIOR_ID.BE_SPECIFIC,
    COGNITIVE_BEHAVIOR_ID.EXAMINE_EVIDENCE,
    COGNITIVE_BEHAVIOR_ID.SEMANTIC_METHOD,
    COGNITIVE_BEHAVIOR_ID.RE_ATTRIBUTION,
  ],
} as const satisfies Record<CognitiveErrorId, readonly CognitiveBehaviorId[]>;

/**
 * ✅ UI에서 바로 쓰기 편한 헬퍼 (id -> 객체 매핑)
 */
const BEHAVIOR_BY_ID = Object.fromEntries(
  COGNITIVE_BEHAVIORS.map((b) => [b.id, b])
) as Record<CognitiveBehaviorId, (typeof COGNITIVE_BEHAVIORS)[number]>;

export function getRecommendedBehaviors(errorId: CognitiveErrorId) {
  return COGNITIVE_ERROR_RECOMMENDED_BEHAVIOR_IDS[errorId].map(
    (behaviorId) => BEHAVIOR_BY_ID[behaviorId]
  );
}
